baseURL = "https://chungman.kim/"
languageCode = "en-us"
title = "chungman.kim"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Blog"
        url = "/blog/"
        weight = 2
    [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 3
    [[menu.main]]
        name = "Tags"
        url = "/tags/"
        weight = 4

[params]
    [[params.social]]
        url = "https://www.linkedin.com/in/chungmankim/"
        name = "linkedin"
        weight = 1
    [[params.social]]
        url = "https://github.com/choongmanee"
        name = "github"
        weight = 2
